kind: Deployment
apiVersion: apps/v1
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      process_type: worker
  replicas: 2
  template:
    metadata:
      labels:
        process_type: worker
    spec:
      containers:
        - name: worker
          image: "{{ images.main.url }}"
          imagePullPolicy: Always
          command:
            - bundle
            - exec
            - ruby
            - script/worker.rb
          volumeMounts:
            - name: config
              mountPath: /opt/postal/config
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: postal-config
