kind: Service
apiVersion: v1
metadata:
  name: smtp
  {% if config.smtpMetalLBAddressPool %}
  metallb.universe.tf/address-pool: {{ config.smtpMetalLBAddressPool}}
  {% endif %}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 25
      targetPort: 2525
  selector:
    process_type: smtp
