kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: postal-web
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  rules:
    - host: "{{ config.domain }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: web
              servicePort: 80
  tls:
    - hosts:
      - "{{ config.domain }}"
      secretName: tls-certs
